# Default values for efk.

# https://github.com/komljen/helm-charts/blob/master/kibana/values.yaml
kibana:
  image:
    repository: "docker.elastic.co/kibana/kibana-oss"
    tag: "6.4.2"
  env:
    # All Kibana configuration options are adjustable via env vars.
    # To adjust a config option to an env var uppercase + replace `.` with `_`
    # Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
    #
    ELASTICSEARCH_URL: http://elasticsearch-efk-cluster:9200
    SERVER_PORT: 5601
    LOGGING_VERBOSE: "true"
    SERVER_DEFAULTROUTE: "/app/kibana"

# https://github.com/komljen/helm-charts/blob/master/elasticsearch/values.yaml
elasticsearch:
  image:
    repository: quay.io/pires/docker-elasticsearch-kubernetes
    tag: "6.4.2"
  name: efk-cluster
  clientReplicas: 1
  masterReplicas: 1
  dataReplicas: 1
  dataVolumeSize: 10Gi
  javaOpts: "-Xms1024m -Xmx1024m"
  resources:
    requests:
      memory: 1024Mi
      cpu: 200m
    limits:
      memory: 2048Mi
      cpu: '1'
  storage:
    # e.g. gp2 for AWS
    type: gp2
    # e.g. kubernetes.io/aws-ebs for AWS
    classProvisioner: kubernetes.io/aws-ebs
    # Retain or Delete
    reclaimPolicy: Delete

# https://github.com/kubernetes/charts/blob/master/stable/fluent-bit/values.yaml
fluent-bit:
  image:
    fluent_bit:
      repository: fluent/fluent-bit
      tag: 1.0.2
  backend:
    type: es
    es:
      host: elasticsearch-efk-cluster
      port: 9200
      index: kubernetes_cluster
      logstash_prefix: kubernetes_cluster

# https://github.com/helm/charts/blob/master/stable/elasticsearch-curator/values.yaml
elasticsearch-curator:
  config:
    elasticsearch:
      hosts:
        - elasticsearch-efk-cluster
